
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `Loja` DEFAULT CHARACTER SET utf8 ;
USE `Loja` ;

CREATE TABLE IF NOT EXISTS `Loja`.`Estado` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `UF` VARCHAR(2)  NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Loja`.`Municipio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Estado_ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CodIBGE` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Municipio_Estado_idx` (`Estado_ID` ASC),
  CONSTRAINT `fk_Municipio_Estado`
    FOREIGN KEY (`Estado_ID`)
    REFERENCES `Loja`.`Estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Loja`.`Cliente` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(80) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `Celular` VARCHAR(11) NULL,
  `EndLogradouro` VARCHAR(100) NOT NULL,
  `EndNumero` VARCHAR(45) NOT NULL,
  `EndMunicipio` INT NULL,
  `EndCEP` VARCHAR(45) NOT NULL,
  `Municipio_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Cliente_Municipio1_idx` (`Municipio_ID` ASC),
  CONSTRAINT `fk_Cliente_Municipio1`
    FOREIGN KEY (`Municipio_ID`)
    REFERENCES `Loja`.`Municipio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Loja`.`ContaReceber` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Cliente_ID` INT NOT NULL,
  `FaturaVendaID` INT NOT NULL,
  `DataConta` DATE NOT NULL,
  `DataVencimento` DATE NOT NULL,
  `Valor` DECIMAL NOT NULL,
  `Situacao` ENUM("1", "2", "3") NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Cliente_ID_idx` (`Cliente_ID` ASC),
  CONSTRAINT `Cliente_ID`
    FOREIGN KEY (`Cliente_ID`)
    REFERENCES `Loja`.`Cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
